### ISSUE TITLE
Named Constant Error

### ISSUE THREAD

**Issue by jrguenther** [rails/actioncable-examples#1]
I didn't have redis installed yet, so I did `brew install redis`. 

Then I ran:

0. Started redis in it's own terminal with `redis-server`
1. Run ./bin/setup in terminal session A
2. Run ./bin/cable in terminal session A
3. Run ./bin/rails server terminal session B
4. Visit http://localhost:3000

The site loads on the both browsers and when I click "Post Comment" I get

```
NameError (uninitialized constant ActionCable::Server::Broadcasting::Redis):
  app/jobs/comment_relay_job.rb:3:in `perform'
  app/models/comment.rb:5:in `block in <class:Comment>'
  app/controllers/comments_controller.rb:5:in `create'
```

Any idea what might be wrong?

**Comment by habermann24** [comment]
Do a `bundle update` or require 'redis' in an initializer.
Was fixed just a few ours ago in actioncable

**Comment by jrguenther** [comment]
I just saw dhh's commit. Thanks, that fixed it.
