### ISSUE TITLE
Streaming not working

### ISSUE THREAD

**Issue by sai43** [rails/actioncable-examples#11]
Hi,
I had clone this project and run in local machine. Live Streaming not worked perfectly.
I don't know why this is happen to me..!
When I refresh my browser then i'll see the latest data on view until not streamed.

checkout this video: https://www.dropbox.com/s/6fzr5r6srz61bb8/rails_action_cable.mov?dl=0

**Comment by cbilgili** [comment]
+1

**Comment by wazery** [comment]
+1

**Comment by wazery** [comment]
I get it to work after checking this https://github.com/rails/actioncable/issues/66. Just make sure you stick to either `127.0.0.1` or `localhost`.

**Comment by rushingfitness** [comment]
I made sure both were pointing localhost, however I still have this issue. Any thoughts?

https://www.dropbox.com/home?preview=ActionCable.mov

**Comment by rushingfitness** [comment]
Here is a second video with that last example setup seeming like it should work without any hijacking logging issues, but still no bueno.

https://www.dropbox.com/s/49lczekx99d7xz3/ActionCable%20Take%202.mov?dl=0

**Comment by rushingfitness** [comment]
^^ Tacking onto that, I've added logs into each function (especially paying attention to `events.message`) of the gempath `actioncable/lib/assets/javascripts/cable/connection.coffee`.

I'm not seeing any messages coming through JS side from the broadcast I am making server side. Perhaps there isn't a connection from Redis <=> WS <=> Client-Side?

**Comment by rushingfitness** [comment]
So following up more on this, I was able to get a message through the front end (not correctly though), by  commenting out the `-> (message) do` proc line in `lib/action_cable/channel/streams.rb`, exposing just the `transmit ActiveSupport::JSON.decode(message), via: "streamed from #{broadcasting}"` line. This transmitted to the front end correctly. So I'm assuming that whatever/where ever is calling this proc to actually fire the transmit line? Anybody have any thoughts

**Comment by rushingfitness** [comment]
Finally got my issue fixed. It was a Redis setting problem with ActionCable itself: https://github.com/rails/actioncable/pull/124

**Comment by sai43** [comment]
Yeah it's worked for me with login different browsers,and for chat with same channel.
