### ISSUE TITLE
Question: Turbolinks and ActionCable

### ISSUE THREAD

**Issue by assimovt** [rails/actioncable-examples#15]
I've got a question regarding Turoblinks and ActionCable. I see in [here](/rails/actioncable-examples/blob/master/app/views/layouts/application.html.erb#L8), the meta tag is used to store information about the current user. Since Turbolinks does not update the ```head``` section, there is a little problem with this approach when for instance one needs to store a "room" or a "company" and user may be switching between these entities, hence the Cable subscriptions won't be updated. So, I was just wondering what's the best way to deal with it? Thanks!

**Comment by assimovt** [comment]
I could actually set `data-no-turbolink` to the links that change the scope. Still thinking if there is a better way, without a full page refresh.

**Comment by dhh** [comment]
You can hide page specific configuration inside the DOM that changes. So for example, you might have `<div data-behavior="chat_room" data-room-id="45">` and then you use that to alter the subscription.

You can also use custom tags. Here are a few snippets from Basecamp for inspiration:

```coffeescript
BC.Chat.createRoom = (element) ->
  BC.cable.subscriptions.create channel: "ChatChannel", room_number: element.dataset.roomNumber,
    element: element
    ...

BC.registerElement "bc-chat-room",
  attachedCallback: ->
    BC.ready =>
      @room = BC.Chat.createRoom(this)

  detachedCallback: ->
    @room?.leave()
```

**Comment by dhh** [comment]
Please post future questions on StackOverflow or similar, btw. We use the issues to track only bugs, not usage questions. Thanks!

**Comment by assimovt** [comment]
Thanks @dhh :+1:
