### ISSUE TITLE
Rails 5 Updates

### ISSUE THREAD

**Issue by HayleyCAnderson** [rails/actioncable-examples#16]
There have been quite a few setup changes since this example was created which are now in the Rails 5 beta version. Is there an intention to update or replace this example accordingly? Or to remove the link to this repository from the Action Cable README entirely? I would be happy to contribute any of these changes, but would like to know what is preferred.

**Comment by dhh** [comment]
Would be nice to upgrade this repo to use latest Rails 5, so the examples
are current.

**Comment by HayleyCAnderson** [comment]
Okay, I can start working on that this weekend.

**Comment by garettarrowood** [comment]
That would be excellent :).

**Comment by HayleyCAnderson** [comment]
Addressed by #17
