### ISSUE TITLE
Possible memory leaks

### ISSUE THREAD

**Issue by Markowy** [rails/actioncable-examples#24]
#### Steps to reproduce
1. Clone and run application.
2. Watch RSS memory consumed by puma process (`ps aux | grep puma`).
3. Perform large number of requests to websockets endpoint, which can be done with e.g. `thor` node library with the following command `thor -C 20 --amount 500 ws://localhost:28080`.

There is no need to create a subscription, plain connection to ws endpoint, confirmed by `Registered connection` (and optionally `Finished`) messages in logs, is enough.

#### Observations
Cold `puma` start consumes around 70MB of RSS, however, consumed memory size increases constantly with each `thor` run (and hangs on some level even if all of connections are closed).
The same issue can be observed without any additional tools.

I tested it against ruby `2.1.6`, `2.2.2` and `2.3`, archived version of [actioncable](https://github.com/rails/actioncable) and also the newest one (used in this repository). The same issue appears also after replacing `puma` with `unicorn`.

**Comment by sun1752709589** [comment]
i met the same problem!!!

**Comment by Markowy** [comment]
Good to know, but seems like nobody really cares :smile:

I ended up with restarting `puma` worker processes via `puma_worker_killer` (standalone version of `actioncable`). Of course, those memory leaks could be related to the applications' code itself, but as far as I remember, the same issue appears also for brand new `rails` app.
